import Head from "next/head";
import Table from "./components/Table";
import Create from "./components/Create";

export default function Home() {
  return (
    <>
      <Head>
        <title>Services Orders API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full">
        <Table />
        <Create />
      </main>
    </>
  );
}
