import Head from "next/head";
import Table from "./components/Table";
import CreateServiceForm from "./components/Create";
import CreateClientForm from "./components/CreateClient";
import { Button } from "react-bootstrap";
import { useState } from "react";
import TableClient from "./components/TableClient";

export default function Home() {
  const [modalClient, setModalClient] = useState(false);
  return (
    <>
      <Head>
        <title>Services Orders API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous"
        />
      </Head>
      <main className="d-flex flex-column align-items-center justify-content-center w-full">
        <Table />
        <TableClient />
        <div className="d-flex gap-3">
          {!modalClient && <CreateServiceForm />}
          {modalClient && <CreateClientForm />}
        </div>
        <Button className="mt-5" onClick={() => setModalClient(!modalClient)} variant="primary">
          {modalClient ? "Criar serviço" : "Criar Cliente"}
        </Button>
      </main>
    </>
  );
}
